Feature/new types
TouchInstinct/api-generator-templates pull request #73
Opened 2019-04-26 12:51 UTC by ZharaOo

Examples of test classes with new features

[TestClasses.zip](https://github.com/TouchInstinct/api-generator-templates/files/3121351/TestClasses.zip)

2019-04-29 06:07 UTC, petropavel13 requested changes

2019-04-29 06:07 UTC, petropavel13 commented on Swift/blocks/class/copy-declaration.twig
> +{% if containsOptionalFields %}
we need to be able to copy with new parameters even if there is an optional fields

2019-04-29 06:07 UTC, petropavel13 commented on Swift/blocks/class/copy-declaration.twig
> +{%- set containsOptionalFields = false -%}
seems that is redundant

2019-04-29 06:07 UTC, petropavel13 commented on Swift/macroses/common.utils.twig
> +        let formatter = NumberFormatter()
for performance purpose it should be rendered like ApiDateFormattingService

2019-04-29 06:07 UTC, petropavel13 commented on Swift/macroses/complexField.utils.twig
> +        self.{{ field.name }} = DateInRegion(seconds: TimeInterval({{ field.name }}), region: .local)
don't pass region. timestamp, usually, uses UTC

2019-04-29 06:07 UTC, petropavel13 commented on Swift/macroses/common.utils.twig
> -{% macro defaultValueForField(field) %}
revert please, we need default values for non-optional types

2019-04-29 11:36 UTC, ZharaOo commented on Swift/blocks/class/copy-declaration.twig
> +{% if containsOptionalFields %}
To copy object with new parameters we can use copyWith method declared above in this file

2019-05-16 11:45 UTC, petropavel13 requested changes

2019-05-16 11:45 UTC, petropavel13 commented on Swift/blocks/class/copy-declaration.twig
> +{% if containsOptionalFields %}
maybe you mean `if !containsOptionalFields` ?

2019-05-16 11:45 UTC, petropavel13 commented on Swift/ApiNumberFormattingService.swift.twig
> +        case .decimal:
switch is useless for now

2019-05-16 11:45 UTC, petropavel13 commented on Swift/macroses/common.utils.twig
> +{% macro formatStrongOrNullableOptional(field, strong) %}
I don't understand what does mean `strong` here. Can you rename it to something more clear?

2019-05-16 11:45 UTC, petropavel13 commented on Swift/macroses/common.utils.twig
> +    ApiNumberFormattingService.shared.string(from: {{ field.name -}}, format: .decimal)
shared is required?

2019-05-16 11:45 UTC, petropavel13 commented on Swift/macroses/complexField.utils.twig
> +        {%- set stringDecimalInit = "ApiNumberFormattingService.shared.decimalNumber(from: %s, format: .decimal)"|format(field.name) -%}
shared is required?

2019-05-17 09:48 UTC, ZharaOo commented on Swift/blocks/class/copy-declaration.twig
> +{% if containsOptionalFields %}
That is a declaration of 'copyWithout' method. We decided that we can copy a class only without optional fields. So if class doesn't contains optional fields we don't need to declare this method.

2019-05-20 11:37 UTC, petropavel13 approved these changes

2019-05-20 11:39 UTC, merged