Feature/date patterns
TouchInstinct/api-generator-templates pull request #87
Opened 2019-08-02 14:28 UTC by Hiraev

2019-08-02 14:38 UTC, petropavel13 approved these changes

2019-08-02 14:41 UTC, Hiraev commented
`package name` будет подставлять генератор

2019-08-04 00:30 UTC, BlizzedRu requested changes

2019-08-04 00:30 UTC, BlizzedRu commented on KotlinOutputFiles/DateFactory.kt
> +            if (typeName == dateTimeName) DateTimeJsonAdapter(formatAnnotation.patterns)
Нужно поставить { } если условие не помещается целиком на одну строку

2019-08-04 00:30 UTC, BlizzedRu commented on KotlinOutputFiles/AbstractDateJsonAdapter.kt
> +        const val CANT_FIND_ANY_FORMATTERS = "Can't find any DateTimeFormatter"
private?

2019-08-04 00:30 UTC, BlizzedRu commented on KotlinOutputFiles/AbstractDateJsonAdapter.kt
> +        } ?: throw JsonEncodingException(LOCAL_DATE_CANNOT_BE_NULL)
Вроде как нет смысла вынесения строки, т.к. использование только здесь

2019-08-04 00:30 UTC, BlizzedRu commented on KotlinOutputFiles/AbstractDateJsonAdapter.kt
> +        throw IllegalArgumentException(CANT_FIND_ANY_FORMATTERS)
скорее лучше написать отдельный метод с метанием ошибки типа  `{assert/throw}CantFindFormatter`,но есть подозрение, что это вкусовщина

2019-08-04 00:30 UTC, BlizzedRu commented on KotlinOutputFiles/DateFactory.kt
> +        } else null
плохо читается. Как вариант можно вынести в отдельное условие `if (typeName != dateTimeName && typeName != localDateName) return null`, и следующий return также преобразится

2019-08-07 15:25 UTC, BlizzedRu approved these changes

2019-08-07 15:26 UTC, merged